# netlify.toml

# Build settings
[build]
  # The directory to change to before starting a build
  base = "public"
  # The command to build your site
  command = "npm run build"
  # The publish directory
  publish = "public"

# Basic site settings
[site]
  # Site name
  name = "Portfolio"
  # Site domain
  domain = "DembaIGuess.netlify.app"

# Optional configuration
[context.production.environment]
  # Environment variables specific to production
  NODE_ENV = "production"

# Redirects and headers configuration
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  # Cache static assets for 1 year
  for = "/static/*"
    [headers.values]
      Cache-Control = "public, max-age=31536000"

# Additional configurations...
